### ISSUE TITLE
SAR ADC 

### ISSUE THREAD

**Issue by Newisere** [NeuroFan/Algorithmic-SAR-ADC-simulation-files#1]
There is a problem: no such a matlab file update_digits here! Could you update your repository?

**Comment by NeuroFan** [comment]
updated!

**Comment by Newisere** [comment]
There is another problem: sar adc ignores negative part of the signal. Is it correct?

**Comment by NeuroFan** [comment]
yes of course, you must DC shift the signal; many practical ADCs require that

sorry I did not see the message
